'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import type { ContentMeta, ContentRevision, Honour, SiteContent } from '../../db/site-content';
import { normaliseSiteContent } from '../../lib/site-content-rules';
import type { NewsCardItem } from '../../lib/club-news';

type Section = keyof SiteContent;
type ListSection = Exclude<Section, 'contact' | 'links'>;
type FieldDefinition = { key: string; label: string; wide?: boolean; textarea?: boolean; placeholder?: string; type?: 'text' | 'number' | 'date' | 'time' | 'datetime-local' | 'checkbox'; options?: Array<{ value: string; label: string }> };
type SectionDefinition = { label: string; title: string; description: string; page: string; singular: string; fields: FieldDefinition[] };

const definitions: Record<ListSection, SectionDefinition> = {
  notices: { label: 'Club noticeboard', title: 'Club noticeboard', description: 'Official notices shown beneath fixtures on the homepage.', page: '/#community', singular: 'notice', fields: [{ key: 'title', label: 'Heading', wide: true }, { key: 'category', label: 'Category' }, { key: 'label', label: 'Top label' }, { key: 'copy', label: 'Notice text', wide: true, textarea: true }, { key: 'action', label: 'Button wording' }, { key: 'href', label: 'Button link', wide: true }, { key: 'publishAt', label: 'Show from (optional)', type: 'datetime-local' }, { key: 'expiresAt', label: 'Remove after (optional)', type: 'datetime-local' }] },
  fixtures: { label: 'Fixtures & results', title: 'Upcoming fixtures', description: 'Choose a date and time so every fixture is displayed consistently. These fields will be filled automatically when the Foireann feed is connected.', page: '/#fixtures', singular: 'fixture', fields: [{ key: 'day', label: 'Match date', type: 'date' }, { key: 'time', label: 'Throw-in time', type: 'time' }, { key: 'timeTbc', label: 'Time not confirmed', type: 'checkbox' }, { key: 'team', label: 'Team' }, { key: 'tag', label: 'Competition' }, { key: 'game', label: 'Fixture', wide: true }, { key: 'venue', label: 'Venue', wide: true }, { key: 'publishAt', label: 'Show from (optional)', type: 'datetime-local' }, { key: 'expiresAt', label: 'Remove after (optional)', type: 'datetime-local' }] },
  results: { label: 'Fixtures & results', title: 'Recent results', description: 'Record the match date and scores, with an optional report link.', page: '/#results', singular: 'result', fields: [{ key: 'date', label: 'Match date', type: 'date' }, { key: 'team', label: 'Team' }, { key: 'competition', label: 'Competition', wide: true }, { key: 'home', label: 'Home team' }, { key: 'homeScore', label: 'Home score' }, { key: 'away', label: 'Away team' }, { key: 'awayScore', label: 'Away score' }, { key: 'reportUrl', label: 'Match report link', wide: true }] },
  updates: { label: 'News', title: 'Club news', description: 'Publish full club-authored news stories or link to an external report.', page: '/news', singular: 'news story', fields: [{ key: 'date', label: 'Article date', type: 'date' }, { key: 'title', label: 'Headline', wide: true }, { key: 'summary', label: 'Summary', wide: true, textarea: true }, { key: 'body', label: 'Full article', wide: true, textarea: true }, { key: 'image', label: 'Image address', wide: true }, { key: 'imageAlt', label: 'Image description', wide: true }, { key: 'href', label: 'Optional external link', wide: true }, { key: 'action', label: 'Button wording' }, { key: 'publishAt', label: 'Publish from (optional)', type: 'datetime-local' }, { key: 'expiresAt', label: 'Remove after (optional)', type: 'datetime-local' }] },
  gallery: { label: 'Homepage photos', title: 'Homepage photographs', description: 'The first two approved photographs are shown on the homepage. Use the arrow controls to choose which appear first.', page: '/#gallery', singular: 'photograph', fields: [{ key: 'alt', label: 'Accessible description', wide: true }, { key: 'caption', label: 'Caption', wide: true }, { key: 'image', label: 'Image address', wide: true }, { key: 'publishAt', label: 'Show from (optional)', type: 'datetime-local' }, { key: 'expiresAt', label: 'Remove after (optional)', type: 'datetime-local' }] },
  sponsors: { label: 'Sponsors', title: 'Club sponsors', description: 'Set each partner’s position using 1 for first, 2 for second, 3 for third and so on.', page: '/sponsorship', singular: 'sponsor', fields: [{ key: 'name', label: 'Business name', wide: true }, { key: 'tier', label: 'Sponsorship tier' }, { key: 'sortOrder', label: 'Display position', placeholder: '1', type: 'number' }, { key: 'href', label: 'Website', wide: true }, { key: 'image', label: 'Logo address', wide: true }, { key: 'style', label: 'Logo colour treatment', options: [{ value: 'standard', label: 'Standard light background' }, { value: 'cti', label: 'CTI white background' }, { value: 'mcardle', label: 'McArdle Doyle dark background' }, { value: 'lynch', label: 'Michael Lynch red background' }] }, { key: 'publishAt', label: 'Show from (optional)', type: 'datetime-local' }, { key: 'expiresAt', label: 'Remove after (optional)', type: 'datetime-local' }] },
  shops: { label: 'Club shop', title: 'Shop providers', description: 'Add every approved retailer that sells St. Mochtas club gear. Position 1 is shown first.', page: '/shop', singular: 'shop provider', fields: [{ key: 'name', label: 'Provider name', wide: true }, { key: 'sortOrder', label: 'Display position', placeholder: '1', type: 'number' }, { key: 'href', label: 'Shop website', wide: true }, { key: 'description', label: 'What this provider sells', wide: true, textarea: true }, { key: 'image', label: 'Optional logo address', wide: true }, { key: 'publishAt', label: 'Show from (optional)', type: 'datetime-local' }, { key: 'expiresAt', label: 'Remove after (optional)', type: 'datetime-local' }] },
  officers: { label: 'Committee', title: 'Club committee', description: 'Names and public contact details on the Contact page.', page: '/contact', singular: 'officer', fields: [{ key: 'role', label: 'Role' }, { key: 'name', label: 'Name' }, { key: 'email', label: 'Public email', wide: true }] },
  history: { label: 'History', title: 'Club history timeline', description: 'Maintain the historical chapters on the dedicated History page.', page: '/history', singular: 'chapter', fields: [{ key: 'period', label: 'Period' }, { key: 'title', label: 'Chapter heading', wide: true }, { key: 'text', label: 'History text', wide: true, textarea: true }, { key: 'note', label: 'Supporting note', wide: true, textarea: true }] },
  honours: { label: 'Honours', title: 'Roll of honour', description: 'Maintain men’s, ladies’ and underage competition records.', page: '/honours', singular: 'honour', fields: [{ key: 'category', label: 'Section' }, { key: 'sortOrder', label: 'Position in section', type: 'number' }, { key: 'competition', label: 'Competition', wide: true }, { key: 'detail', label: 'Competition detail', wide: true }, { key: 'years', label: 'Winning years' }, { key: 'team', label: 'Team name', wide: true }, { key: 'note', label: 'Record note', wide: true, textarea: true }] },
};

const editorTabOrder: Array<Section | 'archive'> = ['updates', 'fixtures', 'notices', 'history', 'honours', 'archive', 'links', 'shops', 'sponsors', 'officers', 'contact', 'gallery'];
const sectionOrder = editorTabOrder.filter((key): key is Section => key !== 'archive');
const sectionLabels: Record<Section, string> = { ...Object.fromEntries(Object.entries(definitions).map(([key, value]) => [key, value.label])) as Record<ListSection, string>, links: 'Membership & links', contact: 'Contact details' };
const blank: Record<ListSection, Record<string, string>> = {
  notices: { label: 'New notice', category: 'Club update', title: '', copy: '', href: '/contact', action: 'Read more', publishAt: '', expiresAt: '' }, fixtures: { day: '', time: '', timeTbc: 'false', team: '', game: '', venue: '', tag: 'Fixture', publishAt: '', expiresAt: '' }, results: { date: '', team: '', competition: '', home: '', homeScore: '', away: '', awayScore: '', reportUrl: '' }, updates: { date: '', title: '', summary: '', body: '', image: '', imageAlt: '', href: '', action: 'Read more', publishAt: '', expiresAt: '' }, gallery: { image: '', alt: '', caption: '', publishAt: '', expiresAt: '' }, sponsors: { name: '', href: '', image: '', style: 'standard', tier: 'Club partner', sortOrder: '1', publishAt: '', expiresAt: '' }, shops: { name: '', description: '', href: '', image: '', sortOrder: '1', publishAt: '', expiresAt: '' }, officers: { role: '', name: '', email: '' }, history: { period: '', title: '', text: '', note: '' }, honours: { category: 'men', competition: '', detail: '', years: '', team: '', note: '', sortOrder: '1' },
};

function normaliseDisplayPositions(content: SiteContent): SiteContent {
  return normaliseSiteContent(content);
}

function formatAdminNewsDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Latest' : new Intl.DateTimeFormat('en-IE', { day: 'numeric', month: 'short', year: 'numeric' }).format(date); }

export default function AdminContentManager({ archiveManager, latestNews }: { archiveManager?: React.ReactNode; latestNews: NewsCardItem[] }) {
  const [published, setPublished] = useState<SiteContent | null>(null); const [content, setContent] = useState<SiteContent | null>(null); const [drafts, setDrafts] = useState<Partial<SiteContent>>({}); const [meta, setMeta] = useState<Partial<Record<Section, ContentMeta>>>({}); const [revisions, setRevisions] = useState<ContentRevision[]>([]); const [section, setSection] = useState<Section>('updates'); const [showArchive, setShowArchive] = useState(false); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState(false); const [historyOpen, setHistoryOpen] = useState(false);
  const load = useCallback(async () => { setMessage('Loading the website editor…'); try { const response = await fetch('/api/admin/content', { cache: 'no-store', credentials: 'same-origin' }); const data = await response.json() as { content?: SiteContent; drafts?: Partial<SiteContent>; meta?: Partial<Record<Section, ContentMeta>>; revisions?: ContentRevision[]; error?: string }; if (!response.ok || !data.content) throw new Error(data.error ?? 'The website content could not be loaded.'); const publishedContent = normaliseDisplayPositions(data.content); const editableContent = normaliseDisplayPositions({ ...publishedContent, ...(data.drafts ?? {}) }); setPublished(publishedContent); setDrafts(data.drafts ?? {}); setMeta(data.meta ?? {}); setRevisions(data.revisions ?? []); setContent(editableContent); setMessage(''); } catch (error) { setMessage(error instanceof Error ? error.message : 'The website editor could not connect.'); } }, []);
  useEffect(() => { const selectFromLocation = () => { const requested = new URLSearchParams(window.location.search).get('section') as Section | null; if (requested && (sectionOrder.includes(requested) || requested === 'results')) { setSection(requested); setShowArchive(false); } else setShowArchive(window.location.hash === '#archive-manager'); }; selectFromLocation(); window.addEventListener('hashchange', selectFromLocation); void load(); return () => window.removeEventListener('hashchange', selectFromLocation); }, [load]);
  useEffect(() => { if (!preview) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setPreview(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [preview]);
  const dirtySections = useMemo(() => { const changed = new Set<Section>(); if (!content || !published) return changed; for (const key of Object.keys(content) as Section[]) { const saved = drafts[key] ?? published[key]; if (JSON.stringify(content[key]) !== JSON.stringify(saved)) changed.add(key); } return changed; }, [content, drafts, published]);
  useEffect(() => { if (!dirtySections.size) return; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirtySections]);
  const hasDraft = section in drafts;
  const isDirty = dirtySections.has(section);
  const sectionRevisions = useMemo(() => revisions.filter((item) => item.section === section), [revisions, section]);
  async function refreshSavedSection(savedSection: Section) { const response = await fetch('/api/admin/content', { cache: 'no-store', credentials: 'same-origin' }); const data = await response.json() as { content?: SiteContent; drafts?: Partial<SiteContent>; meta?: Partial<Record<Section, ContentMeta>>; revisions?: ContentRevision[]; error?: string }; if (!response.ok || !data.content) throw new Error(data.error ?? 'The saved website content could not be refreshed.'); const nextPublished = normaliseDisplayPositions(data.content); const nextDrafts = data.drafts ?? {}; const nextSaved = normaliseDisplayPositions({ ...nextPublished, ...nextDrafts }); setPublished(nextPublished); setDrafts(nextDrafts); setMeta(data.meta ?? {}); setRevisions(data.revisions ?? []); setContent((current) => current ? { ...current, [savedSection]: nextSaved[savedSection] } : nextSaved); }
  async function save(mode: 'draft' | 'publish') { if (!content || busy) return; const savingSection = section; setBusy(true); setMessage(mode === 'draft' ? 'Saving draft…' : 'Publishing changes…'); try { const response = await fetch('/api/admin/content', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ section: savingSection, data: content[savingSection], mode }) }); const raw = await response.text(); let data: { error?: string } = {}; try { data = raw ? JSON.parse(raw) as { error?: string } : {}; } catch { /* use the clear fallback below */ } if (!response.ok) throw new Error(data.error ?? (response.status === 401 ? 'Your sign-in has expired. Sign in again, then return to this section.' : 'The update could not be saved. Your changes are still on this screen.')); await refreshSavedSection(savingSection); setMessage(mode === 'draft' ? `${sectionLabels[savingSection]} draft saved. It is private until you publish it.` : `${sectionLabels[savingSection]} published on the website.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'The update could not be saved. Your changes are still on this screen.'); } finally { setBusy(false); } }
  async function restore(id: number) { if (!window.confirm('Restore and publish this earlier version?')) return; const restoringSection = section; setBusy(true); try { const response = await fetch('/api/admin/content', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ restoreId: id }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? 'Restore failed.'); await refreshSavedSection(restoringSection); setMessage(`${sectionLabels[restoringSection]} restored and published.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Restore failed.'); } finally { setBusy(false); } }
  function updateItem(index: number, field: string, value: string) { if (!content || section === 'contact' || section === 'links') return; const items = [...content[section]] as Array<Record<string, string>>; if ((section === 'sponsors' || section === 'shops') && field === 'sortOrder' && value) { const position = Math.max(1, Math.min(items.length, Number.parseInt(value, 10) || 1)); const [moved] = items.splice(index, 1); items.splice(position - 1, 0, moved); items.forEach((item, itemIndex) => { items[itemIndex] = { ...item, sortOrder: String(itemIndex + 1) }; }); } else items[index] = { ...items[index], [field]: value }; setContent({ ...content, [section]: items }); }
  function addItem() { if (!content || section === 'contact' || section === 'links') return; const item = { ...blank[section] }; if (section === 'sponsors' || section === 'shops') item.sortOrder = String(content[section].length + 1); setContent({ ...content, [section]: [...content[section], item] as never }); }
  function removeItem(index: number) { if (!content || section === 'contact' || section === 'links') return; const items = content[section].filter((_, itemIndex) => itemIndex !== index) as Array<Record<string, string>>; if (section === 'sponsors' || section === 'shops') items.forEach((item, itemIndex) => { items[itemIndex] = { ...item, sortOrder: String(itemIndex + 1) }; }); setContent({ ...content, [section]: items as never }); }
  function moveItem(index: number, offset: -1 | 1) { if (!content || section === 'contact' || section === 'links' || section === 'honours' || section === 'sponsors' || section === 'shops') return; const items = [...content[section]]; const destination = index + offset; if (destination < 0 || destination >= items.length) return; [items[index], items[destination]] = [items[destination], items[index]]; setContent({ ...content, [section]: items as never }); }
  function updateHonour(index: number, field: keyof Honour, value: string) {
    if (!content) return;
    const items = [...content.honours];
    const current = items[index];
    if (!current) return;
    if (field === 'category') {
      const category = value as Honour['category'];
      items[index] = { ...current, category, sortOrder: String(items.filter((item) => item.category === category).length + 1) };
    } else if (field === 'sortOrder') {
      const categoryIndices = items.map((item, itemIndex) => ({ item, itemIndex })).filter(({ item }) => item.category === current.category).sort((a, b) => Number(a.item.sortOrder || 0) - Number(b.item.sortOrder || 0));
      const from = categoryIndices.findIndex(({ itemIndex }) => itemIndex === index);
      const to = Math.max(0, Math.min(categoryIndices.length - 1, (Number.parseInt(value, 10) || 1) - 1));
      const [moved] = categoryIndices.splice(from, 1);
      categoryIndices.splice(to, 0, moved);
      categoryIndices.forEach(({ itemIndex }, position) => { items[itemIndex] = { ...items[itemIndex], sortOrder: String(position + 1) }; });
    } else items[index] = { ...current, [field]: value };
    setContent(normaliseDisplayPositions({ ...content, honours: items }));
  }
  function addHonour(category: Honour['category']) { if (!content) return; const item = { ...blank.honours, category, sortOrder: String(content.honours.filter((honour) => honour.category === category).length + 1) } as Honour; setContent({ ...content, honours: [...content.honours, item] }); }
  function removeHonour(index: number) { if (!content) return; setContent(normaliseDisplayPositions({ ...content, honours: content.honours.filter((_, itemIndex) => itemIndex !== index) })); }
  async function uploadContentImage(index: number, file: File) { if (!content || !['gallery', 'updates', 'sponsors', 'shops'].includes(section)) return; const item = (content[section] as Array<Record<string, string>>)[index]; const altText = section === 'gallery' ? item.alt : section === 'updates' ? item.imageAlt : item.name; if (!altText?.trim()) { setMessage(section === 'updates' ? 'Add an image description before uploading the news image.' : section === 'gallery' ? 'Describe the photograph before uploading it.' : 'Add the business or provider name before uploading its logo.'); return; } setBusy(true); try { const form = new FormData(); form.set('file', file); form.set('altText', altText); const response = await fetch('/api/admin/media', { method: 'POST', body: form, credentials: 'same-origin' }); const data = await response.json() as { url?: string; error?: string }; if (!response.ok || !data.url) throw new Error(data.error ?? 'The image could not be uploaded.'); updateItem(index, 'image', data.url); setMessage('Image uploaded into this section. Save a draft or publish when ready.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'The image could not be uploaded.'); } finally { setBusy(false); } }
  function resetUnsavedChanges() { if (!content || !published) return; const saved = drafts[section] ?? published[section]; setContent({ ...content, [section]: saved }); setMessage('Unsaved changes removed.'); }
  async function discardDraft() { if (!content || !published || !hasDraft || busy || !window.confirm(`Discard the saved ${sectionLabels[section]} draft and return to the public version?`)) return; const discardedSection = section; setBusy(true); try { const response = await fetch(`/api/admin/content?section=${encodeURIComponent(discardedSection)}`, { method: 'DELETE', credentials: 'same-origin' }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? 'The saved draft could not be discarded.'); setDrafts((current) => { const next = { ...current }; delete next[discardedSection]; return next; }); setContent((current) => current && published ? { ...current, [discardedSection]: published[discardedSection] } : current); setMessage(`${sectionLabels[discardedSection]} draft discarded. The public version is back in the editor.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'The saved draft could not be discarded.'); } finally { setBusy(false); } }
  if (!content) return <section className="admin-content-card admin-editor-loading"><p>{message || 'Loading website editor…'}</p><button type="button" onClick={() => void load()}>Try again</button></section>;
  const definition = section !== 'contact' && section !== 'links' ? definitions[section] : null; const last = meta[section];
  return <section className="admin-content-card">
    <div className="admin-section-heading"><div><p className="eyebrow blue">Club website editor</p><h2>Update, review and publish.</h2></div><p>Save work as a draft, review it here, then publish it when it is ready. Every published version can be restored.</p></div>
    <nav className="admin-content-tabs" aria-label="Website sections">{editorTabOrder.map((key) => { if (key === 'archive') return <button key={key} type="button" className={showArchive ? 'active' : ''} onClick={() => { setShowArchive(true); window.history.replaceState({}, '', `${window.location.pathname}#archive-manager`); setPreview(false); setHistoryOpen(false); setMessage(''); }}>Club archive</button>; const active = !showArchive && (section === key || (key === 'fixtures' && section === 'results')); const draftSaved = key === 'fixtures' ? ('fixtures' in drafts || 'results' in drafts) : key in drafts; const unsaved = key === 'fixtures' ? (dirtySections.has('fixtures') || dirtySections.has('results')) : dirtySections.has(key); return <button key={key} type="button" className={active ? 'active' : ''} onClick={() => { setSection(key); setShowArchive(false); window.history.replaceState({}, '', `${window.location.pathname}?section=${key}#website-editor`); setPreview(false); setHistoryOpen(false); setMessage(''); }}>{sectionLabels[key]}{unsaved ? <i className="unsaved" aria-label="Unsaved changes" /> : draftSaved && <i aria-label="Draft saved" />}</button>; })}</nav>
    {showArchive && <div id="archive-manager" className="admin-archive-within-editor">{archiveManager}</div>}
    <div id="website-editor" hidden={showArchive}>
    {(section === 'fixtures' || section === 'results') && <nav className="admin-match-tabs" aria-label="Fixtures and results"><button type="button" className={section === 'fixtures' ? 'active' : ''} onClick={() => { setSection('fixtures'); setPreview(false); setHistoryOpen(false); setMessage(''); }}>Upcoming fixtures</button><button type="button" className={section === 'results' ? 'active' : ''} onClick={() => { setSection('results'); setPreview(false); setHistoryOpen(false); setMessage(''); }}>Recent results</button></nav>}
    {message && <p className="admin-message" role="status">{message}</p>}
    <div className="admin-current-section"><span>Editing: <strong>{sectionLabels[section]}</strong>{isDirty ? <em className="unsaved">Unsaved changes</em> : hasDraft && <em>Saved draft</em>}</span><div>{definition && <a href={definition.page}>View public page <b>↗</b></a>}</div></div>
    {last && <p className="admin-last-updated">Last published by <strong>{last.updatedBy}</strong> on {new Date(last.updatedAt).toLocaleString('en-IE')}.</p>}
    {section === 'updates' && <section className="admin-live-news"><div className="admin-editor-title"><div><p className="eyebrow blue">Currently on the public News page</p><h3>Latest monitored coverage</h3><p>These articles are found and refreshed automatically each day. They are shown here for reference and do not need to be edited. Use Club news below for stories published directly by St. Mochtas.</p></div><a href="/news">View full News page ↗</a></div>{latestNews.length > 0 ? <div className="admin-live-news-grid">{latestNews.map((item, index) => <article key={`${item.url}-${index}`}><div className="news-card-meta"><span>{item.source} · {item.matchLabel}</span><time>{formatAdminNewsDate(item.date)}</time></div><h4>{item.title}</h4><p>{item.summary}</p><a href={item.url} target="_blank" rel="noreferrer">{item.format} original ↗</a></article>)}</div> : <p className="admin-empty-inline">No monitored St. Mochtas articles are available at the moment. The feeds will be checked again automatically.</p>}</section>}
    {definition && section !== 'honours' && <div className="admin-editor-panel"><div className="admin-editor-title"><div><h3>{definition.title}</h3><p>{definition.description}</p></div><button type="button" onClick={addItem}>+ Add {definition.singular}</button></div><div className="admin-editor-list">{(content[section] as Array<Record<string, string>>).map((item, index, items) => <article className="admin-editor-row" key={index}><header><strong>{item.title || item.competition || item.game || item.name || item.role || `${definition.singular} ${index + 1}`}</strong><div className="admin-row-actions">{section !== 'sponsors' && section !== 'shops' && <><button type="button" disabled={index === 0} onClick={() => moveItem(index, -1)} aria-label="Move up">↑</button><button type="button" disabled={index === items.length - 1} onClick={() => moveItem(index, 1)} aria-label="Move down">↓</button></>}<button type="button" className="admin-remove-row" onClick={() => removeItem(index)}>Remove</button></div></header>{['gallery', 'updates', 'sponsors', 'shops'].includes(section) && item.image && <img className="admin-content-image" src={item.image} alt={section === 'gallery' ? item.alt || '' : section === 'updates' ? item.imageAlt || '' : item.name || ''} />}<div className="admin-editor-fields">{definition.fields.map((field) => <Field key={field.key} label={field.label} value={item[field.key] ?? ''} wide={field.wide} textarea={field.textarea} placeholder={field.placeholder} type={field.type} options={field.options} onChange={(value) => updateItem(index, field.key, value)} />)}{['gallery', 'updates', 'sponsors', 'shops'].includes(section) && <label className="admin-content-upload">{item.image ? 'Replace uploaded image' : 'Upload an image'}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadContentImage(index, file); event.currentTarget.value = ''; }} /></label>}</div></article>)}</div>{(content[section] as unknown[]).length === 0 && <p className="admin-empty-inline">No items yet. Use the add button to create one.</p>}</div>}
    {section === 'honours' && <HonoursEditor honours={content.honours} onAdd={addHonour} onRemove={removeHonour} onChange={updateHonour} />}
    {section === 'contact' && <ObjectEditor title="Club contact details" description="Used on the Contact page and general enquiry links." values={content.contact} fields={[['email','Club email'],['address','Postal address'],['eircode','Eircode'],['directionsUrl','Directions link'],['mapUrl','Embedded map address']]} onChange={(key, value) => setContent({ ...content, contact: { ...content.contact, [key]: value } })} />}
    {section === 'links' && <div className="admin-link-groups"><ObjectEditor title="Membership" description="The registration link used on the Membership page and homepage support button." values={content.links} fields={[['membership','Clubforce membership page']]} onChange={(key, value) => setContent({ ...content, links: { ...content.links, [key]: value } })} /><ObjectEditor title="Official social accounts" description="These account links feed the homepage, News page, gallery and footer. Change them here whenever the club moves to a new account." values={content.links} fields={[['facebook','Facebook account'],['instagram','Instagram account'],['x','X account']]} onChange={(key, value) => setContent({ ...content, links: { ...content.links, [key]: value } })} /><ObjectEditor title="County links in the footer" description="Official Louth GAA and Louth LGFA destinations shown throughout the website footer." values={content.links} fields={[['louthGaa','Louth GAA website'],['louthLgfa','Louth LGFA website']]} onChange={(key, value) => setContent({ ...content, links: { ...content.links, [key]: value } })} /></div>}
    {preview && <PreviewDialog section={section} content={content} definition={definition} onClose={() => setPreview(false)} />}
    <div className="admin-publish-bar"><div className="admin-publish-actions"><button type="button" onClick={() => void save('draft')} disabled={busy}>{busy ? 'Please wait…' : 'Save draft'}</button><button type="button" onClick={() => setPreview(true)} disabled={busy}>Review changes</button>{isDirty && <button type="button" onClick={resetUnsavedChanges} disabled={busy}>Undo unsaved changes</button>}{hasDraft && <button type="button" onClick={() => void discardDraft()} disabled={busy}>Discard saved draft</button>}</div><p className={`admin-action-status${message || isDirty ? ' visible' : ''}`} aria-live="polite">{message || (isDirty ? 'This section has unsaved changes.' : 'Changes stay private until you publish them.')}</p><button className="button button-yellow admin-publish-primary" type="button" onClick={() => void save('publish')} disabled={busy}><small>Make changes public</small>Publish {sectionLabels[section]} <span>→</span></button></div>
    <div className="admin-revisions"><button type="button" className="admin-history-toggle" onClick={() => setHistoryOpen(!historyOpen)}>{historyOpen ? 'Hide' : 'Show'} version history ({sectionRevisions.length})</button>{historyOpen && <div>{sectionRevisions.length === 0 ? <p>No earlier published versions yet.</p> : sectionRevisions.map((revision) => <article key={revision.id}><span><strong>{revision.action === 'restored' ? 'Restored version' : 'Published version'}</strong><small>{revision.updatedBy} · {new Date(revision.updatedAt).toLocaleString('en-IE')}</small></span><button type="button" onClick={() => void restore(revision.id)} disabled={busy}>Restore</button></article>)}</div>}</div>
    </div>
  </section>;
}

const honourGroups: Array<{ key: Honour['category']; label: string; description: string }> = [
  { key: 'men', label: 'Men’s adult honours', description: 'Competitions won by the adult men’s teams.' },
  { key: 'ladies', label: 'Ladies’ adult honours', description: 'Competitions won by the adult ladies’ teams.' },
  { key: 'underage', label: 'Underage honours', description: 'Titles won by St. Mochtas, St. Vincent’s and amalgamated teams.' },
];

function HonoursEditor({ honours, onAdd, onRemove, onChange }: { honours: Honour[]; onAdd: (category: Honour['category']) => void; onRemove: (index: number) => void; onChange: (index: number, field: keyof Honour, value: string) => void }) {
  return <div className="admin-honours-groups">{honourGroups.map((group) => {
    const records = honours.map((honour, index) => ({ honour, index })).filter(({ honour }) => honour.category === group.key).sort((a, b) => Number(a.honour.sortOrder || 0) - Number(b.honour.sortOrder || 0));
    return <section className="admin-editor-panel admin-honours-group" key={group.key}><div className="admin-editor-title"><div><h3>{group.label}</h3><p>{group.description} Positions are numbered within this section only.</p></div><button type="button" onClick={() => onAdd(group.key)}>+ Add competition</button></div><div className="admin-editor-list">{records.map(({ honour, index }) => <article className="admin-editor-row" key={`${group.key}-${index}`}><header><strong>{honour.competition || 'New competition'}</strong><button type="button" onClick={() => onRemove(index)}>Remove</button></header><div className="admin-editor-fields"><label>Section<select value={honour.category} onChange={(event) => onChange(index, 'category', event.target.value)}><option value="men">Men’s adult honours</option><option value="ladies">Ladies’ adult honours</option><option value="underage">Underage honours</option></select></label><Field label="Position in this section" type="number" value={honour.sortOrder} onChange={(value) => onChange(index, 'sortOrder', value)} /><Field label="Competition" value={honour.competition} wide onChange={(value) => onChange(index, 'competition', value)} /><Field label="Competition detail (optional)" value={honour.detail} wide onChange={(value) => onChange(index, 'detail', value)} /><WinningYearsField value={honour.years} onChange={(value) => onChange(index, 'years', value)} />{honour.category === 'underage' && <><Field label="Team name" value={honour.team} wide onChange={(value) => onChange(index, 'team', value)} /><Field label="Record note (optional)" value={honour.note} wide textarea onChange={(value) => onChange(index, 'note', value)} /></>}</div></article>)}</div>{records.length === 0 && <p className="admin-empty-inline">No honours have been added to this section yet.</p>}</section>;
  })}</div>;
}

function WinningYearsField({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const [nextYear, setNextYear] = useState('');
  const years = Array.from(new Set(value.match(/\b(?:18|19|20|21)\d{2}\b/g) ?? [])).sort((a, b) => Number(a) - Number(b));
  const save = (next: string[]) => onChange(next.sort((a, b) => Number(a) - Number(b)).join(' · '));
  const add = () => { if (!/^\d{4}$/.test(nextYear) || Number(nextYear) < 1800 || Number(nextYear) > 2199 || years.includes(nextYear)) return; save([...years, nextYear]); setNextYear(''); };
  return <fieldset className="admin-years-field"><legend>Winning years</legend><div className="admin-year-chips">{years.map((year) => <button type="button" key={year} onClick={() => save(years.filter((item) => item !== year))} title={`Remove ${year}`}>{year}<span aria-hidden="true">×</span></button>)}</div><div className="admin-year-add"><input type="number" min="1800" max="2199" step="1" value={nextYear} placeholder="e.g. 2025" aria-label="Add a winning year" onChange={(event) => setNextYear(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); add(); } }} /><button type="button" onClick={add} disabled={!/^\d{4}$/.test(nextYear) || years.includes(nextYear)}>Add year</button></div><small>Select a year above to remove it. Years are automatically placed in chronological order.</small></fieldset>;
}

function PreviewDialog({ section, content, definition, onClose }: { section: Section; content: SiteContent; definition: SectionDefinition | null; onClose: () => void }) {
  const value = content[section];
  const listItems = definition && Array.isArray(value) ? value as unknown as Array<Record<string, string>> : null;
  const objectValue = value as unknown as Record<string, string>;
  return <div className="admin-preview-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-preview" role="dialog" aria-modal="true" aria-labelledby="admin-preview-title"><header><div><small>Review before publishing</small><strong id="admin-preview-title">{sectionLabels[section]}</strong></div><button type="button" onClick={onClose} aria-label="Close review">Close ×</button></header><div className="admin-preview-body">{definition && listItems ? listItems.length ? listItems.map((item, index) => <article key={index}><h3>{item.title || item.competition || item.game || item.name || item.role || `${definition.singular} ${index + 1}`}</h3><dl>{definition.fields.filter((field) => item[field.key]).map((field) => <div key={field.key}><dt>{field.label}</dt><dd>{field.type === 'checkbox' ? (item[field.key] === 'true' ? 'Yes' : 'No') : item[field.key]}</dd></div>)}</dl></article>) : <p>No items are currently included in this section.</p> : <article><dl>{Object.entries(objectValue).map(([key, item]) => <div key={key}><dt>{key.replace(/([A-Z])/g, ' $1')}</dt><dd>{item}</dd></div>)}</dl></article>}</div><footer><p>This is a private content review. Use “View public page” to check the current live design.</p><button type="button" className="button button-yellow" onClick={onClose}>Continue editing</button></footer></section></div>;
}

function Field({ label, value, onChange, wide = false, textarea = false, placeholder = '', type = 'text', options }: Omit<FieldDefinition, 'key'> & { value: string; onChange: (value: string) => void }) {
  if (type === 'checkbox') return <label className={`admin-checkbox${wide ? ' wide' : ''}`}><input type="checkbox" checked={value === 'true'} onChange={(event) => onChange(event.target.checked ? 'true' : 'false')} /><span>{label}</span></label>;
  if (options) return <label className={wide ? 'wide' : ''}>{label}<select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select></label>;
  const isLegacy = (type === 'date' && !!value && !/^\d{4}-\d{2}-\d{2}$/.test(value)) || (type === 'time' && !!value && !/^\d{2}:\d{2}$/.test(value));
  const inputValue = type === 'datetime-local' ? toLocalDateTime(value) : isLegacy ? '' : value;
  const update = (next: string) => onChange(type === 'datetime-local' && next ? new Date(next).toISOString() : next);
  return <label className={wide ? 'wide' : ''}>{label}{textarea ? <textarea rows={4} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /> : <input type={type} min={type === 'number' ? 1 : undefined} step={type === 'number' ? 1 : undefined} value={inputValue} placeholder={placeholder} onChange={(event) => update(event.target.value)} />}{isLegacy && <small className="admin-field-note">Previously entered as “{value}”. Select a date or time to standardise it.</small>}</label>;
}
function toLocalDateTime(value: string) { if (!value) return ''; const date = new Date(value); if (Number.isNaN(date.getTime())) return value.slice(0, 16); const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); }
function ObjectEditor({ title, description, values, fields, onChange }: { title: string; description: string; values: Record<string, string>; fields: string[][]; onChange: (key: string, value: string) => void }) { return <div className="admin-editor-panel"><div className="admin-editor-title"><div><h3>{title}</h3><p>{description}</p></div></div><div className="admin-editor-fields">{fields.map(([key, label]) => <Field key={key} label={label} value={values[key] ?? ''} wide textarea={key === 'address'} onChange={(value) => onChange(key, value)} />)}</div></div>; }
