import { env } from 'cloudflare:workers';
import { siteContentSchemaStatements } from './schema';
import { normaliseSection, normaliseSiteContent } from '../lib/site-content-rules';

export type PublishingFields = { publishAt?: string; expiresAt?: string };
export type Notice = PublishingFields & { label: string; category: string; title: string; copy: string; href: string; action: string };
export type Fixture = PublishingFields & { day: string; time: string; timeTbc?: string; team: string; game: string; venue: string; tag: string };
export type Result = PublishingFields & { date: string; team: string; competition: string; home: string; homeScore: string; away: string; awayScore: string; reportUrl: string };
export type ClubUpdate = PublishingFields & { date: string; title: string; summary: string; body: string; image: string; imageAlt: string; href: string; action: string };
export type Sponsor = PublishingFields & { name: string; href: string; image: string; style: 'standard' | 'cti' | 'mcardle' | 'lynch'; tier: string; sortOrder: string };
export type ShopProvider = PublishingFields & { name: string; description: string; href: string; image: string; sortOrder: string };
export type Officer = { role: string; name: string; email: string };
export type GalleryImage = PublishingFields & { image: string; alt: string; caption: string };
export type ContactDetails = { email: string; address: string; eircode: string; mapUrl: string; directionsUrl: string };
export type HistoryChapter = { period: string; title: string; text: string; note: string };
export type Honour = { category: 'men' | 'ladies' | 'underage'; competition: string; detail: string; years: string; team: string; note: string; sortOrder: string };
export type ClubLinks = { membership: string; facebook: string; instagram: string; x: string; louthGaa: string; louthLgfa: string };

export type SiteContent = { notices: Notice[]; fixtures: Fixture[]; results: Result[]; updates: ClubUpdate[]; sponsors: Sponsor[]; shops: ShopProvider[]; officers: Officer[]; gallery: GalleryImage[]; history: HistoryChapter[]; honours: Honour[]; contact: ContactDetails; links: ClubLinks };
export type ContentSection = keyof SiteContent;
export type ContentMeta = { updatedBy: string; updatedAt: string };
export type ContentRevision = { id: number; section: ContentSection; action: string; updatedBy: string; updatedAt: string };

const history: HistoryChapter[] = [
  { period: '1886 to 1934', title: 'Gaelic games in Louth Village', text: 'The history of Gaelic games in the village predates St. Mochtas. A 2009 anniversary account records GAA activity in Louth Village from 1886 and the first known match by a team representing the village in February 1887. That game was played against Knockbridge at Stonetrough. Contemporary club and newspaper records date the formation of St. Mochtas GFC to 1934.', note: 'Stonetrough is the earliest playing place named in the surviving newspaper record.' },
  { period: '1934 to 1944', title: 'The first honours', text: 'Success came quickly to the new club. St. Mochtas won the Junior 2A competition in 1935, the Junior A League in 1936 and the Louth Junior Football Championship in 1944. Those early teams established the club in county competition during its first decade.', note: 'The 1944 Junior Championship was the first of five won by the men.' },
  { period: '1950s and 1960s', title: 'A permanent home at Artoney', text: 'The club added another Junior 2A success in 1956 before a major step forward off the field. Páirc Mochta at Artoney gave St. Mochtas a home of its own. It was officially opened on 16 June 1961 with a match between Louth and Offaly. St. Mochtas then won the Junior 2A League in 1969.', note: 'Fifty years after the opening, the club marked the occasion with Mass, juvenile games and Louth playing Cavan.' },
  { period: '1970s', title: 'Football and club life', text: 'The decade began with Junior 2A success in 1970, followed by the Junior A League in 1973 and the Junior Football Championship in 1975. Club life extended well beyond match days. Business was conducted in the old hall in Louth Village, while the annual dinner dance at the Fairways Hotel was described in 1972 as the main social occasion of the club year.', note: 'a former committee member recalled being asked to join the committee in 1968 when he was only thirteen or fourteen.' },
  { period: '1980s', title: 'A first Intermediate Championship', text: 'St. Mochtas won the Louth Intermediate Football Championship in 1981, a major landmark in the club’s progress. The Dealgan Milk Products Shield followed in 1984 as the club continued to compete and develop at adult level.', note: 'The 1981 title was the club’s first Intermediate Championship.' },
  { period: '1990s', title: 'St. Vincent’s and a strong decade', text: 'For a period, the Louth Village underage section was known as St. Vincent’s. County records list St. Joseph’s/St. Vincent’s as the 1994 Louth minor champions, and early 2000s fixtures still used the combined name. At adult level, St. Mochtas won the Kevin Mullen Shield in 1990 and 1991 before lifting the Junior Football Championship again in 1995.', note: 'The St. Vincent’s name remains an important part of the memories of players who came through the club’s underage teams.' },
  { period: '2002 to 2006', title: 'Ladies football and new clubrooms', text: 'The ladies section began in 2002, bringing a new group of players, mentors and families into St. Mochtas. The men won the Junior Football Championship and Kevin Mullen Shield in 2004. At the same time, major work was taking place at Artoney. By 2003 the club reported that about €300,000 had been spent on the ground, and the new dressing rooms and clubrooms were officially opened on 18 May 2005 when Louth played Monaghan.', note: 'Páirc Mochta also hosted the Leinster Junior Hurling final in 2006.' },
  { period: '2007 to 2012', title: 'Success across the club', text: 'In 2007 both adult men’s teams won their leagues in the same year for the first time. The Junior Football Championship returned to Páirc Mochta in 2009, the same year the juvenile field was blessed during the club anniversary weekend. In 2010 the ladies won their first Intermediate Championship, and in 2012 they marked ten years with a family weekend and a senior nine-a-side title.', note: 'This period joined success on the field with a stronger underage and ladies structure.' },
  { period: '2013 to 2019', title: 'Building towards senior football', text: 'Underage teams and club amalgamations continued to provide a pathway into the adult game. The men won the Intermediate Football Championship for a second time in 2018 and moved into the senior grade. Development at Páirc Mochta continued too, with the new stand and gym blessed during a club celebration weekend in 2019.', note: 'The facilities grew in stages through the work of committees, members, families and local supporters.' },
  { period: '2020 to 2025', title: 'A new senior chapter', text: 'St. Mochtas reached the Louth Senior Football Championship final for the first time in 2021. The men won the Cardinal O’Donnell Cup in 2023 and regained the Division 1 title in 2025. In 2024 the village welcomed home Craig Lennon after his PwC Football All-Star selection and Eimear Byrne after her selection on the TG4 Junior Team of the Championship. The ladies won the Intermediate Championship and Division 2 League in 2025, earning a return to senior football for 2026.', note: 'Full competition records are kept on the separate Roll of Honour page.' },
  { period: '2024 onwards', title: 'The all-weather pitch project', text: 'St. Mochtas joined Phase 6 of the GAA Healthy Club programme in 2024 and received a €200,000 sports capital allocation towards an enclosed all-weather pitch. A 2025 planning application proposed a 65m by 28m pitch, floodlights and changes to the walking track.', note: 'The proposed work is the latest phase in the development of Páirc Mochta.' },
];

const honours: Honour[] = [
  ['men','Cardinal O’Donnell Cup','Louth Division 1 League','2023 · 2025','','','10'], ['men','Louth Intermediate Football Championship','','1981 · 2018','','','20'], ['men','Louth Junior Football Championship','','1944 · 1975 · 1995 · 2004 · 2009','','','30'], ['men','Louth Junior A Football League','','1936 · 1973 · 2007','','','40'], ['men','Louth Junior 2A Football Championship','','1935 · 1956 · 1970','','','50'], ['men','Louth Junior 2A Football League','','1969','','','60'], ['men','Louth Junior 2 Football League','Later recorded as Division 4C','2007 · 2014','','','70'], ['men','St. Jude’s All-Ireland Junior Football 7s Shield','','2005 · 2010','','','80'], ['men','Dealgan Milk Products Shield','','1984','','','90'], ['men','Avonmore / Kevin Mullen Shield','','1990 · 1991 · 2004','','','100'],
  ['ladies','Louth Ladies Intermediate Football Championship','','2010 · 2025','','','10'], ['ladies','Louth Ladies Division 2 League','','2025','','','20'], ['ladies','Louth Ladies Senior Nine-a-Side','','2012','','','30'],
  ['underage','Louth Minor Football Championship','','1994','St. Joseph’s / St. Vincent’s','St. Vincent’s was the Louth Village underage identity associated with St. Mochtas.','10'], ['underage','Under-18 Division 2 League','','2007','St. Mochtas / St. Bride’s','','20'], ['underage','Under-16 Division 1 Championship','','2007','St. Mochtas / St. Bride’s','','30'], ['underage','Under-16 Division 1 League','','2007','St. Mochtas / St. Bride’s','','40'], ['underage','Under-15 All-County League','','2007','St. Bride’s / St. Mochtas','Won after a final replay against Geraldines.','50'], ['underage','Under-13 Féile title','','2007','St. Mochtas','','60'], ['underage','Ladies Under-16 B League','','2011','St. Mochtas Ladies','','70'],
].map(([category, competition, detail, years, team, note, sortOrder]) => ({ category: category as Honour['category'], competition, detail, years, team, note, sortOrder }));

export const defaultSiteContent: SiteContent = {
  fixtures: [{ day: '2026-08-24', time: '20:00', timeTbc: 'false', team: 'Senior Men', game: 'Ardee St. Mary’s v St. Mochtas', venue: 'Louth GAA Training Centre, Darver', tag: 'Championship' }, { day: '2026-08-26', time: '19:00', timeTbc: 'false', team: 'U13 Boys', game: 'Seán O’Mahony’s v St. Mochtas', venue: 'Point Road', tag: 'League' }, { day: '2026-09-02', time: '19:00', timeTbc: 'false', team: 'U13 Boys', game: 'St. Mochtas v Clan na nGael', venue: 'Páirc Mochta', tag: 'League' }],
  results: [],
  notices: [{ label: 'Pinned notice', category: 'Club development', title: 'AstroTurf development', copy: 'Planning, fundraising and project updates will be shared here as the club’s AstroTurf development moves forward.', href: '/contact', action: 'Contact the club' }, { label: 'Can you lend a hand?', category: 'Volunteers', title: 'Help around the club', copy: 'Volunteer call-outs, club work days and ways to help with teams, events and the grounds will be posted here.', href: '/contact', action: 'Get involved' }, { label: 'Dates for the diary', category: 'Club events', title: 'Upcoming club events', copy: 'Fundraisers, volunteer days and community events will be added as soon as dates are confirmed.', href: '/news', action: 'View club updates' }],
  updates: [], history, honours,
  sponsors: [{ name: 'CTI Business Solutions', href: 'https://www.cti.ie/', image: 'https://static.wixstatic.com/media/6e6166_5ac41548842942a08f2a44a36be4879a~mv2.png/v1/crop/x_0,y_15,w_420,h_269/fill/w_394,h_252,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/CTI-Logo-Navy%20Transparent.png', style: 'cti', tier: 'Main club partner', sortOrder: '1' }, { name: 'McArdle Doyle', href: 'https://www.mcardledoyle.ie/', image: 'https://static.wixstatic.com/media/e244d4_ff2ba677d9d14340b61e75baee0593e1~mv2.png/v1/fill/w_390,h_141,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/McArdle%20Doyle%20Logo%20-%202025%20White.png', style: 'mcardle', tier: 'Main club partner', sortOrder: '2' }, { name: 'Michael Lynch Menswear', href: 'https://michaellynchmenswear.ie/', image: 'https://michaellynchmenswear.ie/cdn/shop/files/Michael_Lynch_Menswear_Logo_eb4ca05a-8c37-4248-9324-949bd19214a9_1.png?v=1727951676&width=600', style: 'lynch', tier: 'Main club partner', sortOrder: '3' }],
  shops: [{ name: 'O’Neills', description: 'Official St. Mochtas GFC jerseys, training wear, leisurewear and accessories for adults and children.', href: 'https://www.oneills.com/shop-by-team/gaa/ireland/st-mochtas-gfc-louth.html', image: '', sortOrder: '1' }],
  officers: [{ role: 'Chairperson', name: 'Club Chairperson', email: 'chairperson@example.com' }, { role: 'Secretary', name: 'Club Secretary', email: 'secretary@example.com' }, { role: 'Treasurer', name: 'Club Treasurer', email: 'treasurer@example.com' }, { role: 'PRO', name: 'Club PRO', email: 'pro@example.com' }, { role: "Children's Officer", name: "Club Children's Officer", email: '' }],
  gallery: [{ image: 'https://s0.geograph.org.uk/geophotos/05/08/03/5080314_7f43ce64.jpg', alt: "St Mochta's House beside the Augustinian priory ruins in Louth Village", caption: "St. Mochta's House, Louth Village" }, { image: 'https://mmo.aiircdn.com/301/68986ec1c9cb9.jpg', alt: "St. Mochtas celebrating the Cardinal O'Donnell Cup", caption: "Cardinal O'Donnell Cup · 2025" }],
  contact: { email: 'club-contact@example.com', address: 'Club grounds\\nCounty Louth', eircode: '', mapUrl: '', directionsUrl: '' },
  links: { membership: 'https://clubs.clubforce.com/clubs/st-mochtas-gfc-events-louth/', facebook: 'https://www.facebook.com/p/StMochtas-GFC-100033954378543/', instagram: 'https://www.instagram.com/st.mochtas/', x: 'https://x.com/StMochtas1934', louthGaa: 'https://louthgaa.ie/', louthLgfa: 'https://louthlgfa.ie/' },
};

type ContentEnvironment = Cloudflare.Env & { DB?: D1Database; ARCHIVE?: R2Bucket };
function runtime() { return env as ContentEnvironment; }
export function isVisible(item: PublishingFields, now = new Date()) { const start = item.publishAt ? Date.parse(item.publishAt) : NaN; const end = item.expiresAt ? Date.parse(item.expiresAt) : NaN; return (Number.isNaN(start) || start <= now.getTime()) && (Number.isNaN(end) || end > now.getTime()); }
export function visibleItems<T extends PublishingFields>(items: T[]) { return items.filter((item) => isVisible(item)); }
export async function ensureSiteContentSchema(db: D1Database) { await db.batch(siteContentSchemaStatements.map((statement) => db.prepare(statement))); await db.prepare('PRAGMA optimize').run(); }
export async function getSiteContent(): Promise<SiteContent> { const db = runtime().DB; if (!db) return normaliseSiteContent(defaultSiteContent); await ensureSiteContentSchema(db); const rows = await db.prepare('SELECT section, data_json FROM site_content').all<{ section: ContentSection; data_json: string }>(); const content = { ...defaultSiteContent } as SiteContent; for (const row of rows.results) { if (!(row.section in defaultSiteContent)) continue; try { const parsed = JSON.parse(row.data_json); const fallback = defaultSiteContent[row.section]; if (Array.isArray(fallback) !== Array.isArray(parsed) || !parsed || typeof parsed !== 'object') continue; (content as unknown as Record<string, unknown>)[row.section] = Array.isArray(parsed) ? parsed : { ...fallback, ...parsed }; } catch { /* retain defaults */ } } return normaliseSiteContent(content); }
export async function getSiteContentAdminState() { const db = runtime().DB; if (!db) return { content: normaliseSiteContent(defaultSiteContent), drafts: {}, meta: {}, revisions: [] }; await ensureSiteContentSchema(db); const [content, drafts, meta, revisions] = await Promise.all([getSiteContent(), db.prepare('SELECT section, data_json FROM site_content_drafts').all<{ section: ContentSection; data_json: string }>(), db.prepare('SELECT section, updated_by, updated_at FROM site_content').all<{ section: ContentSection; updated_by: string; updated_at: string }>(), db.prepare('SELECT id, section, action, updated_by, updated_at FROM site_content_revisions ORDER BY id DESC LIMIT 80').all<{ id: number; section: ContentSection; action: string; updated_by: string; updated_at: string }>()]); const parsedDrafts: Partial<SiteContent> = {}; for (const row of drafts.results) { if (!(row.section in defaultSiteContent)) continue; try { (parsedDrafts as Record<string, unknown>)[row.section] = normaliseSection(row.section, JSON.parse(row.data_json) as never); } catch { /* ignore damaged draft */ } } const parsedMeta: Partial<Record<ContentSection, ContentMeta>> = {}; for (const row of meta.results) if (row.section in defaultSiteContent) parsedMeta[row.section] = { updatedBy: row.updated_by, updatedAt: row.updated_at }; return { content, drafts: parsedDrafts, meta: parsedMeta, revisions: revisions.results.filter((row) => row.section in defaultSiteContent).map((row) => ({ id: row.id, section: row.section, action: row.action, updatedBy: row.updated_by, updatedAt: row.updated_at })) }; }
export async function saveSiteContentSection<K extends ContentSection>(section: K, data: SiteContent[K], email: string, mode: 'draft' | 'publish' = 'publish') { const db = runtime().DB; if (!db) throw new Error('Website content storage has not been provisioned.'); await ensureSiteContentSchema(db); const now = new Date().toISOString(); const json = JSON.stringify(normaliseSection(section, data)); if (mode === 'draft') { await db.prepare(`INSERT INTO site_content_drafts (section, data_json, updated_by, updated_at) VALUES (?, ?, ?, ?) ON CONFLICT(section) DO UPDATE SET data_json=excluded.data_json, updated_by=excluded.updated_by, updated_at=excluded.updated_at`).bind(section, json, email, now).run(); return; } await db.batch([db.prepare(`INSERT INTO site_content (section, data_json, updated_by, updated_at) VALUES (?, ?, ?, ?) ON CONFLICT(section) DO UPDATE SET data_json=excluded.data_json, updated_by=excluded.updated_by, updated_at=excluded.updated_at`).bind(section, json, email, now), db.prepare('INSERT INTO site_content_revisions (section, data_json, action, updated_by, updated_at) VALUES (?, ?, ?, ?, ?)').bind(section, json, 'published', email, now), db.prepare('DELETE FROM site_content_drafts WHERE section = ?').bind(section)]); }
export async function deleteSiteContentDraft(section: ContentSection) { const db = runtime().DB; if (!db) throw new Error('Website content storage has not been provisioned.'); await ensureSiteContentSchema(db); await db.prepare('DELETE FROM site_content_drafts WHERE section = ?').bind(section).run(); }
export async function restoreSiteContentRevision(id: number, email: string) { const db = runtime().DB; if (!db) throw new Error('Website content storage has not been provisioned.'); await ensureSiteContentSchema(db); const row = await db.prepare('SELECT section, data_json FROM site_content_revisions WHERE id = ?').bind(id).first<{ section: ContentSection; data_json: string }>(); if (!row || !(row.section in defaultSiteContent)) throw new Error('That earlier version could not be found.'); await saveSiteContentSection(row.section, JSON.parse(row.data_json) as never, email, 'publish'); await db.prepare("UPDATE site_content_revisions SET action = 'restored' WHERE id = (SELECT MAX(id) FROM site_content_revisions)").run(); return row.section; }
export function getSiteMediaBindings() { const value = runtime(); return value.DB && value.ARCHIVE ? { db: value.DB, bucket: value.ARCHIVE } : null; }
